@startuml

class Juego
class Pantalla
class Jugador
class Bird
class Tuberia
class Muro
class Colisionable
class Vida

Juego --|> Pantalla
Jugador o-- Pantalla

Bird o-- Arena
Bird *--"3" Vida
Colisionable --*"1" Vida

Jugador o-- Bird

Arena *-- Muro
Arena *-- Tuberia

Tuberia --|> Colisionable
Muro --|> Colisionable

@enduml